import { normalizeScore, normalizeRows, parseWorkbook } from '../js/excel.js';
import { rankPlayers, buildRanking } from '../js/ranking.js';
import { playerStatistics, attendanceStreaks, scoringTrend, regularity, top5Distance } from '../js/statistics.js';
export async function runCalculationTests() {
  const results = [];
  const check = (name, actual, expected) => {
    if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${name}: ${JSON.stringify(actual)} !== ${JSON.stringify(expected)}`);
    results.push(name);
  };
  let warnings = [];
  const warn = (...values) => warnings.push(values);
  [null, undefined, '', '  ', '-', ' - '].forEach((value, i) => check(`Ausencia ${i}`, normalizeScore(value, 'A', 'T', warn), null));
  check('Cero es asistencia', normalizeScore(0, 'A', 'T'), 0);
  check('Decimal español y espacios', normalizeScore(' 7,5 ', 'A', 'T'), 7.5);
  check('Texto inesperado', normalizeScore('lesión', 'Jugadora', '12/09', warn), null);
  check('Warning contextual', warnings[0][0].includes('Jugadora') && warnings[0][0].includes('12/09'), true);
  check('NaN no se propaga', normalizeScore(NaN, 'A', 'T', warn), null);
  check('Booleano no es puntuación', normalizeScore(true, 'A', 'T', warn), null);
  const data = normalizeRows([[' Nombre ', ' T1 ', 'T2'], [' C ', 8, 5], [' B ', 9, '-'], [null, null, null], [' A ', 10, 0]]);
  check('Normaliza cabeceras', data.trainings, ['T1', 'T2']);
  check('Ignora filas vacías', data.players.length, 3);
  const ranking = buildRanking(data.players, 2);
  check('Ranking por puntos', ranking.map(p => p.name), ['C', 'A', 'B']);
  check('Puntos y asistencias', ranking.map(p => [p.points, p.attended]), [[13, 2], [10, 2], [9, 1]]);
  check('Subida y bajadas exactas', ranking.map(p => p.movement), [2, -1, -1]);
  check('Histórico de posiciones', ranking.map(p => p.positions), [[3, 1], [1, 2], [2, 3]]);
  check('Reconstrucción de ranking anterior', rankPlayers(data.players, 1).map(p => p.name), ['A', 'B', 'C']);
  check('Único entrenamiento no comparable', buildRanking(data.players, 1).every(p => p.movement === null), true);
  check('Posición mantenida', buildRanking(normalizeRows([['Nombre', '1', '2'], ['A', 10, 10], ['B', 1, 1]]).players, 2)[0].movement, 0);
  const tie = normalizeRows([['Nombre', '1', '2'], ['Zulu', 5, 5], ['Bea', 10, '-'], ['Ane', 5, 5]]);
  check('Desempate asistencia y alfabético, no media', buildRanking(tie.players, 2).map(p => p.name), ['Ane', 'Zulu', 'Bea']);
  check('Independencia del orden de filas', buildRanking([...tie.players].reverse(), 2).map(p => p.name), ['Ane', 'Zulu', 'Bea']);
  const decimal = normalizeRows([['Nombre', '1', '2'], ['B', 0.1, 0.2], ['A', 0.3, 0]]);
  check('Empates con coma flotante', buildRanking(decimal.players, 2).map(p => p.name), ['A', 'B']);
  const entry = buildRanking(normalizeRows([['Nombre', '1', '2'], ['A', '-', 10], ['B', 5, '-']]).players, 2);
  check('Fila sin puntos previos tiene posición', entry[0].movement, 1);
  const six = buildRanking(Array.from({length: 6}, (_, i) => ({id: String(i), name: `P${i}`, scores: [10-i]})), 1);
  check('Solo cinco destacadas', six.filter(p => p.top5).length, 5);
  check('Distancia dentro', top5Distance(six[0], six), 5);
  check('Distancia fuera', top5Distance(six[5], six), -1);
  check('Menos de seis', top5Distance(six[0], six.slice(0, 5)), null);
  check('Racha actual y máxima', attendanceStreaks([8, 7, null, 9, 8, 7]), {current: 3, best: 3});
  check('Ausencia rompe racha', attendanceStreaks([8, 7, 6, null]), {current: 0, best: 3});
  check('Cero cuenta para racha', attendanceStreaks([0, 0]), {current: 2, best: 2});
  check('Tendencia mejorando', scoringTrend([6, 6, 6, 8, 8, 8]).label, 'Mejorando');
  check('Tendencia bajando', scoringTrend([8, 8, 8, 6, 6, 6]).label, 'Bajando');
  check('Tendencia estable', scoringTrend([8, 8, 8, 8.2, 8.2, 8.2]).label, 'Estable');
  check('Umbral 0,25', scoringTrend([8, 8, 8, 8.25, 8.25, 8.25]).label, 'Mejorando');
  check('Tendencia insuficiente', scoringTrend([8, 7, 9]).label, 'Sin datos suficientes');
  check('Regularidad constante', regularity([8, 8, 8]), 'Muy regular');
  check('Regularidad intermedia', regularity([6, 7, 8]), 'Regular');
  check('Regularidad variable', regularity([1, 5, 9]), 'Variable');
  check('Regularidad insuficiente', regularity([1, 5]), 'Sin datos suficientes');
  const statsPlayers = buildRanking([{id: 'x', name: 'X', scores: [8, 7, null, 9, 8, 7, 9]}], 7);
  const stats = playerStatistics(statsPlayers[0], statsPlayers, ['1', '2', '3', '4', '5', '6', '7']);
  check('Puntos acumulados preservan ausencia', stats.cumulative, [8, 15, 15, 24, 32, 39, 48]);
  check('Puntos últimos 5 calendario', stats.recentPoints, 33);
  check('Media últimas 5 asistencias', stats.recentMean, 8);
  check('Mejor puntuación más reciente', [stats.best, stats.bestTraining], [9, '7']);
  check('Media del equipo ponderada por puntuaciones', stats.teamMean, 8);
  check('Diferencia con equipo', stats.teamDifference, 0);
  const nobody = buildRanking([{id:'n', name:'N', scores:[null, null]}], 2);
  const empty = playerStatistics(nobody[0], nobody, ['1','2']);
  check('Sin asistencias', [empty.average, empty.best, empty.worst, empty.latest, empty.teamMean], [0, null, null, null, null]);
  check('Cualquier número de columnas', normalizeRows([['Nombre', ...Array.from({length:80}, (_, i) => `T${i}`)], ['A', ...Array(80).fill(1)]]).trainings.length, 80);
  check('Sin entrenamientos', normalizeRows([['Nombre'], ['A']]).trainings, []);
  let headerError = false;
  try { normalizeRows([['Otro', 'T1']]); } catch { headerError = true; }
  check('Formato incorrecto detectado', headerError, true);
  const sheet = XLSX.utils.aoa_to_sheet([['Nombre', new Date('2026-09-10T00:00:00Z'), 'Texto'], [' A ', 7.5, '-']]);
  sheet.B1.z = 'dd/mm';
  const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Ranking');
  const parsed = parseWorkbook(XLSX.write(workbook, {type:'array', bookType:'xlsx'}));
  check('Excel real con fecha nativa', parsed.trainings, ['10/09', 'Texto']);
  check('Excel real con decimal y ausencia', parsed.players[0].scores, [7.5, null]);
  return results;
}
